# Generated by Django 5.0.6 on 2024-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setreci',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
