# Generated by Django 5.0.6 on 2024-05-14 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setreci_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='setreci',
            name='kreator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
